---
apiVersion: v1
kind: Secret
metadata:
  name: opengroupware-database-credentials
  namespace: opengroupware
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: opengroupware
type: Opaque
stringData:
  DB_HOST: postgres-primary
  DB_PORT: "5432"
  DB_NAME: opengroupware
  DB_USER: opengroupware
  DB_PASSWORD: CHANGE_ME_IN_PROD
---
apiVersion: v1
kind: Secret
metadata:
  name: opengroupware-jwt-secret
  namespace: opengroupware
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: opengroupware
type: Opaque
stringData:
  JWT_SECRET: CHANGE_ME_IN_PROD
---
apiVersion: v1
kind: Secret
metadata:
  name: opengroupware-rspamd-key
  namespace: opengroupware
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: opengroupware
type: Opaque
stringData:
  RSPAMD_PASSWORD: CHANGE_ME_IN_PROD
