---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: opengroupware
  labels:
    app: loki
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: opengroupware
spec:
  replicas: 1
  serviceName: loki
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: docker.io/grafana/loki:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3100
          args:
            - --config.file=/etc/loki/local-config.yaml
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /loki
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loki-0
  namespace: opengroupware
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: opengroupware
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
      name: http
  selector:
    app: loki
