apiVersion: v2
name: opengroupware-microservice
description: A Helm chart for OpenGroupware microservices
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - rust
  - mail
  - multi-tenant
  - kubernetes
